### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Liyukee** [joyhsu0504/LEFT#1]
hello,I met the issue when I run scripts/trainval-referit3d.py,it said that in "feed_dict['input_str'] = feed_dict['utterance']" TypeError: list indices must be integers or slices, not str. I want to know what type of feed_dict actually?

**Comment by joyhsu0504** [comment]
Hi, feed_dict should be a dict, with utterance set as the following: https://github.com/joyhsu0504/LEFT/blob/main/left/data/referit3d/listening_dataset.py#L261.

**Comment by Liyukee** [comment]
Thanks for your reply. Yes，I guess so.But when I ran the code and I printed the type of feed_dict,it said that the feed_dict is a list actually  whose elements are dict and length is 2. Could you please tell me how to modify the code so that feed_dict can be a dict as expected?Do I have to select one of the elements in feed_dict (such as feed_dict[0] or feed_dict[1])?Or there are some problems in the dataloader?Thank you very much.

**Comment by joyhsu0504** [comment]
Are feed_dict[0] and feed_dict[1] the same? What are the keys for each of the dict? I'm not quite sure why your dataloader is constructed in this way. Thanks!

**Comment by vacancy** [comment]
I have a quick guess. Maybe you are training on two GPUs? @Liyukee  I think the code does not support multi-GPU training.

**Comment by Liyukee** [comment]
The feed_dict[0] and feed_dict[1] are not same,although they have the same keys. @joyhsu0504 
Yes，you are right.I used two GPUs before.And now I try to use just one GPU and the problem of feed_dict is solved.Thanks a lot! @vacancy 
Thank you very much!

**Comment by joyhsu0504** [comment]
Great! Closing issue here.
