### ISSUE TITLE
cannot import name '_mask' from 'jaclearn.vision.coco.pycocotools'

### ISSUE THREAD

**Issue by michalsr** [joyhsu0504/LEFT#2]
I downloaded both Jacinle and Concepts but I encountered this error:
<img width="1785" alt="Screenshot 2024-04-30 at 12 03 51 AM" src="https://github.com/joyhsu0504/LEFT/assets/19779517/7754cf1d-4e74-464e-bae7-94ed9130ef9c">

I downloaded `pycocotools ` but I don't know to download it in Jacinle

**Comment by vacancy** [comment]
It seems that the content of `setup.py` inside `jaclearn/vision/coco` is wrong... Can you copy-paste the file content here and check if it actually matches the file content https://github.com/vacancy/Jacinle/blob/master/jaclearn/vision/coco/setup.py here?

Inside that directory `jaclearn/vision/coco` you can also run `./travis.sh` to test if the package can be successfully compiled.

**Comment by michalsr** [comment]
This is `setup.py`
```from setuptools import setup, Extension
import numpy as np

# To compile and install locally run "python setup.py build_ext --inplace"
# To install library to Python site-packages run "python setup.py build_ext install"

ext_modules = [
    Extension(
        'pycocotools._mask',
        sources=['src/maskApi.c', 'pycocotools/_mask.pyx'],
        include_dirs = [np.get_include(), 'src'],
        extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99'],
    )
]

if __name__ == '__main__':
    setup(
        name='pycocotools',
        packages=['pycocotools'],
        package_dir = {'pycocotools': 'pycocotools'},
        install_requires=[
            'setuptools>=18.0',
            'cython>=0.27.3',
            'matplotlib>=2.1.0'
        ],
        version='2.0',
        ext_modules= ext_modules
    )

```

When I run `./travis.sh`, I get an error 
<img width="1785" alt="Screenshot 2024-04-30 at 7 01 16 PM" src="https://github.com/joyhsu0504/LEFT/assets/19779517/32daff4b-4dad-4483-b047-282222a4d353">
Inside `jaclearn/vision/coco/src`, are files `maskApi.c`, `maskApi.h`,`gason.h` and `gason.cpp`

**Comment by vacancy** [comment]
Thanks! Can you

1) Pull the latest version of Jacinle
2) Delete pycocotools/_mask.c (later a new one will be automatically created)
3) Re-run ./travis.sh

**Comment by michalsr** [comment]
That worked. Thank you so much for the fast reply and fix!
